### ISSUE TITLE
Admin page should show times in specified timezone

### ISSUE THREAD

**Issue by franc6** [ICCM-EU/BOF#191]
Our server is never in the same timezone as our browsers.  Worse, initial setup for each ICCM is done from a third time zone.  Converting correctly is more challenging than it should be, because of this.  It would be nice if I could choose which timezone to display and enter times on the admin page.  Then I don't need to convert at all.   Settings should continue to be saved to the database in the server's timezone.

Choices should include "local timezone" meaning the timezone of the user's browser, and "server timezone", meaning the timezone of the server.

**Comment by tygor** [comment]
FYI, I've started on this in my forked version. As of tonight, the client-side is done. Next I'll handle the server-side (converting the times and new time zone values to UTC before saving).

**Comment by franc6** [comment]
This was fixed with PR #207.  Thanks, @tygor!
