### ISSUE TITLE
Select a programming language and framework

### ISSUE THREAD

**Issue by tpokorra** [ICCM-EU/BOF#2]
I am proposing PHP. Just because you can install it on any server easily.
I am wondering about https://symfony.com/ as a framework. Or is it too heavy? What about https://www.slimframework.com/? But Symfony is quite a standard.

Another option would be Python, with using Django as a framework.

We had C# in the pre conference workshop day in 2016, so I think we should be using something different than C#.

Any thoughts?

**Comment by llevering** [comment]
[Laravel ](https://laravel.com/) is currently very populair in the PHP community. I have to say I like it a lot. Laravel uses a lot of Symfony components, but it is packaged in a really nice way. 

With slim I don' t have experience the idea sounds good and might be very well suited for the BOF system.

As you know I am a PHP programmer so it is hard to comment on Django, but it is a long time around and seems the preferred choice for Python (web) programmers for a very long time, so at least it will be a sensisible choice.
[I don't know if I will be at ICCM, but if so I would really like to join this session]

Edit: If you choose Laravel you can use [Voyager](https://laravelvoyager.com/). It is great for simple CRUD pages (for example: the rooms/locations table you will need, no need to implement that 'by hand') and provides authorisation logic out of the box.

**Comment by ThiasG** [comment]
I find it difficult to choose the framework without knowing the requirements.
What I am able to say: Do not use Python. In most web shared hosting situations you are able to use PHP, but not Python.
To open the discussion to more options: Depending to what we want to achieve, it could be helpful to write an extension e.g. to dokuwiki.
Concerning PHP frameworks: I used fatfree and was happy with it.

**Comment by marcthenomad** [comment]
Happy New Year, everyone!  Is there are a target date for coming to a conclusion about the language and the framework?  I am afraid that I have nothing to add to the discussion, but I am waiting to hear the conclusion.

Well, OK, I will add this comment:  for a small project like this, I wouldn't worry too much about ensuring that we have made the absolute best choice. I am sure that any of the frameworks would work just fine for our needs.  

In regards to language, I would think that PHP would be a better choice. I think that more people will have experience with PHP for web development than Python.

**Comment by saemideluxe** [comment]
I know python much better than PHP and would therefore prefere python (also, imho any sane hosting provider should be able to post-setup a python environment for that matter). But for a hackathon I would with the best known language among the participants which is very likely PHP.

**Comment by marcthenomad** [comment]
Since we have just over a week to go, can we decide on a language and a framework so that those of us who aren't familiar with the framework can get up to speed somewhat before the hackathon?  How are we making this decision? Democratically?  The consensus seems to be to use PHP.  Can we all (or at least a majority) agree to PHP?  

This part may be moot if we decide against PHP, but I will go ahead with it anyway.  In regards to PHP frameworks, I don't see that we have any consensus.  So far we have the following:

- Symfony
- Slim
- Lavarel
- Fatfree

Here is a link to a page that I found that compares these (and other) PHP frameworks:

https://coderseye.com/best-php-frameworks-for-web-developers/

Any thoughts?  

One quick question:  where are we hosting this?  Has this been answered elsewhere?

**Comment by tpokorra** [comment]
I think we don't have time to discuss this anymore, and to find a democratic decision.
So here is the decision: We will go with PHP and Slim.

I will prepare small code snippets illustrating the functionality. I don't think you need to prepare yourself too much for the hackathon. I will prepare a couple of tasks, and we can do them in pair programming or alone, depending what each individual prefers, and helping each other.

In the end, the BOF application is hosted on a Debian server, that runs only during the conference, on site.
But with the code being available on Github, people can run it on their own server for their own conference anywhere.
